#!/usr/bin/bash
# sp11-bluetooth-address@hciN.service: give controller N the public address from /etc/sp11/bluetooth-address
# (raw HCI management, no btmgmt). The helper validates both arguments.
set -eu
. /etc/sp11/bluetooth-address
exec /usr/libexec/sp11/sp11-bt-set-addr "${1#hci}" "$SP11_BT_MAC"
